export const main: string;
export const buttonList: string;
export const imageTab: string;
export const inactiveTab: string;
export const serviceCard: string;
export const serviceLine1: string;
export const price: string;
export const description: string;
export const subTitle: string;
